binary presence

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -30,3 +30,22 @@ jobs:
           fi
           echo "Everything is good ! Keep on coding !"
           exit 0
+
+  compile:
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Checkout GH repository
+        uses: actions/checkout@master
+
+      - name: Compile project
+        run: make
+
+      - name: Check binary presence
+        run: |
+          if [ ! -f ./swapupcase]; then
+            echo "Binary not found"
+            exit 1
+          fi
+          echo "Binary found"
+          exit 0
